-- Consistency fixes coming out of the database audit.
--
-- Hand-written rather than generated: `prisma migrate diff` proposes
-- DROP/CREATE where an ALTER is enough, which would lose the existing rows.
-- The result is verified by replaying the whole migration chain and then
-- comparing it against the datamodel (`npm run db:check-drift`).
--
-- DELIBERATELY NOT INCLUDED HERE (accepted debt, separate API work):
--   * cities.number_of_airports INTEGER -> TEXT and
--     organizations.members / personnel INTEGER -> TEXT. The source data is
--     free text ("20+", "Thousands", "~6 million"): the integer typing is
--     wrong. But src/models/cities.ts and src/models/organizations.ts
--     validate these fields with z.number().int(), and src/db/types.ts
--     declares them as `number`: changing the type in the database would
--     break the corresponding GETs. The import therefore just reports those
--     cells as warnings and writes null.
--   * cities.currency NOT NULL -> nullable, for the same reason
--     (src/models/cities.ts enforces z.string().length(3)).
--   * renaming the "StudyFields" table to study_fields and the
--     user_education_fields.study_field_Id column to study_field_id, which
--     src/db/types.ts (generated by kysely-codegen),
--     src/models/user_education_fields.ts and
--     src/routes/user_education_fields.ts depend on.

-- 3. countries.iso_code carried both @id AND @unique: the redundant unique
--    index duplicated the primary key's own.
DROP INDEX IF EXISTS "countries_iso_code_key";

-- 3bis. Leftover from the _CountryLargestOrganizations ->
--    _OrganizationCountries rename (migrations 20260714000000 and
--    20260718175659): the table, its PK and its B index had been renamed,
--    but not the two foreign key constraints, which kept the old name.
--    Detected by `npm run db:check-drift`.
ALTER TABLE "_OrganizationCountries" RENAME CONSTRAINT "_CountryLargestOrganizations_A_fkey" TO "_OrganizationCountries_A_fkey";
ALTER TABLE "_OrganizationCountries" RENAME CONSTRAINT "_CountryLargestOrganizations_B_fkey" TO "_OrganizationCountries_B_fkey";

-- 4. user_profiles.deleted_at: soft-delete present on nearly every model
--    but missing from this one.
ALTER TABLE "user_profiles" ADD COLUMN "deleted_at" TIMESTAMP(3);

-- 5. personality_questions carried both test_id AND criterion_id with
--    nothing guaranteeing that the criterion belonged to the same test. The
--    composite FK below makes the inconsistency impossible at the database
--    level.
--    Prerequisite: first purge the already-inconsistent rows (none in
--    practice, the table is not populated yet) so the FK can be applied.
DELETE FROM "personality_questions" q
WHERE NOT EXISTS (
  SELECT 1 FROM "personality_criteria" c
  WHERE c."id" = q."criterion_id" AND c."test_id" = q."test_id"
);

CREATE UNIQUE INDEX "personality_criteria_test_id_id_key" ON "personality_criteria"("test_id", "id");

ALTER TABLE "personality_questions" DROP CONSTRAINT "personality_questions_criterion_id_fkey";
ALTER TABLE "personality_questions" ADD CONSTRAINT "personality_questions_test_id_criterion_id_fkey" FOREIGN KEY ("test_id", "criterion_id") REFERENCES "personality_criteria"("test_id", "id") ON DELETE RESTRICT ON UPDATE CASCADE;
