/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthAuthorizationStatus = "approved" | "denied" | "expired" | "pending";

export type AuthOauthClientType = "confidential" | "public";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOauthResponseType = "code";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Certificationcategory = "LANGUAGE" | "OTHER" | "PROFESSIONAL" | "PROJECTMANAGEMENT" | "TECHNICAL" | "VENDORPRODUCT";

export type Contracttype = "APPRENTICESHIP" | "FREELANCE" | "FULL_TIME" | "INTERNSHIP" | "OTHER" | "PART_TIME";

export type Costofliving = "HIGH" | "LOW" | "MEDIUM";

export type Degreelevel = "ASSOCIATE" | "BACHELOR" | "HIGH_SCHOOL" | "MASTER" | "PHD";

export type Difficultylevel = "ADVANCED" | "BEGINNER" | "EXPERT" | "INTERMEDIATE";

export type Educationfieldtype = "MAJOR" | "MINOR";

export type Educationlevel = "BACHELOR" | "HIGH_SCHOOL" | "MASTER" | "NONE" | "OTHER" | "PHD";

export type Employeecountrange = "RANGE_1_10" | "RANGE_1001_5000" | "RANGE_11_50" | "RANGE_201_1000" | "RANGE_5000_PLUS" | "RANGE_51_200";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Governmenttype = "ABSOLUTE_MONARCHY" | "COMMUNIST" | "CONSTITUTIONAL_MONARCHY" | "FEDERATION" | "MILITARY_JUNTA" | "OTHER" | "PARLIAMENTARY" | "REPUBLIC" | "THEOCRACY";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Jobadstatus = "CLOSED" | "DRAFT" | "FILLED" | "PUBLISHED";

export type Jobcategory = "ACADEMIC" | "GOVERNMENT" | "MILITARY" | "NGO" | "OTHER" | "PRIVATE_SECTOR" | "PUBLIC_SECTOR";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Language = "AFRIKAANS" | "ALBANIAN" | "AMHARIC" | "ARABIC" | "ARMENIAN" | "AZERBAIJANI" | "BASQUE" | "BELARUSIAN" | "BENGALI" | "BOSNIAN" | "BULGARIAN" | "BURMESE" | "CATALAN" | "CEBUANO" | "CHINESE_CANTONESE" | "CHINESE_MANDARIN" | "CROATIAN" | "CZECH" | "DANISH" | "DUTCH" | "ENGLISH" | "ESPERANTO" | "ESTONIAN" | "FILIPINO" | "FINNISH" | "FRENCH" | "GALICIAN" | "GEORGIAN" | "GERMAN" | "GREEK" | "GUJARATI" | "HAITIAN_CREOLE" | "HAUSA" | "HEBREW" | "HINDI" | "HUNGARIAN" | "ICELANDIC" | "IGBO" | "INDONESIAN" | "IRISH" | "ITALIAN" | "JAPANESE" | "JAVANESE" | "KANNADA" | "KAZAKH" | "KHMER" | "KOREAN" | "KURDISH" | "KYRGYZ" | "LAO" | "LATIN" | "LATVIAN" | "LITHUANIAN" | "LUXEMBOURGISH" | "MACEDONIAN" | "MALAGASY" | "MALAY" | "MALAYALAM" | "MALTESE" | "MAORI" | "MARATHI" | "MONGOLIAN" | "NEPALI" | "NORWEGIAN" | "PASHTO" | "PERSIAN" | "POLISH" | "PORTUGUESE" | "PUNJABI" | "ROMANIAN" | "RUSSIAN" | "SAMOAN" | "SERBIAN" | "SHONA" | "SINDHI" | "SINHALA" | "SLOVAK" | "SLOVENIAN" | "SOMALI" | "SPANISH" | "SUNDANESE" | "SWAHILI" | "SWEDISH" | "TAJIK" | "TAMIL" | "TATAR" | "TELUGU" | "THAI" | "TIBETAN" | "TURKISH" | "TURKMEN" | "UKRAINIAN" | "URDU" | "UZBEK" | "VIETNAMESE" | "WELSH" | "WOLOF" | "XHOSA" | "YIDDISH" | "YORUBA" | "ZULU";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Organizationsubtype = "ARMY" | "CLUB" | "COMPANY" | "GOVERNMENT" | "INTERNATIONAL_ORGANIZATION" | "NGO" | "NON_PROFIT" | "OTHER" | "RESEARCH_INSTITUTE" | "SOCIETY" | "UNIVERSITY";

export type Qualityoflife = "HIGH" | "LOW" | "MEDIUM";

export type Remotepolicy = "FULL_REMOTE" | "HYBRID" | "ON_SITE";

export type Senioritylevel = "C_LEVEL" | "DIRECTOR" | "ELECTED" | "INTERN" | "JUNIOR" | "LEAD" | "MID" | "OTHER" | "SENIOR";

export type Skillcategory = "FRAMEWORK" | "LANGUAGE" | "METHODOLOGY" | "OTHER" | "SOFT" | "TECHNICAL" | "TOOL";

export type Skillimportance = "NICE_TO_HAVE" | "PREFERRED" | "REQUIRED";

export type StorageBuckettype = "ANALYTICS" | "STANDARD" | "VECTOR";

export type Subjectcategory = "API" | "HARDWARE" | "OTHER" | "PHYSICAL_PRODUCT" | "PLATFORM" | "SERVICE" | "SOFTWARE";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Universitytype = "ACADEMY" | "GRANDE_ECOLE" | "INSTITUTE" | "ONLINE" | "OTHER" | "UNIVERSITY";

export type Userrole = "ADMIN" | "CANDIDATE" | "MODERATOR" | "ORGANIZATION" | "SUPER_ADMIN" | "USER";

export type Userstatus = "ACTIVE" | "DELETED" | "PENDING_VERIFICATION" | "SUSPENDED";

export interface _CityMainIndustries {
  A: string;
  B: string;
}

export interface _CountryLargestOrganizations {
  A: string;
  B: string;
}

export interface _OrganizationIndustries {
  A: string;
  B: string;
}

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface _ProductIndustries {
  A: string;
  B: string;
}

export interface _RelatedIndustries {
  A: string;
  B: string;
}

export interface _WorkingArea {
  A: string;
  B: string;
}

export interface AuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  id: string;
  ip_address: string | null;
  metadata: Json | null;
  user_id: string;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthCustomOauthProviders {
  acceptable_client_ids: Generated<string[]>;
  attribute_mapping: Generated<Json>;
  authorization_params: Generated<Json>;
  authorization_url: string | null;
  cached_discovery: Json | null;
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  custom_claims_allowlist: Generated<string[]>;
  discovery_cached_at: Timestamp | null;
  discovery_url: string | null;
  email_optional: Generated<boolean>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  identifier: string;
  issuer: string | null;
  jwks_uri: string | null;
  name: string;
  pkce_enabled: Generated<boolean>;
  provider_type: string;
  scopes: Generated<string[]>;
  skip_nonce_check: Generated<boolean>;
  token_url: string | null;
  updated_at: Generated<Timestamp>;
  userinfo_url: string | null;
}

export interface AuthFlowState {
  auth_code: string | null;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Timestamp | null;
  email_optional: Generated<boolean>;
  id: string;
  invite_token: string | null;
  linking_target_id: string | null;
  oauth_client_state_id: string | null;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  referrer: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  /**
   * Stores the latest WebAuthn challenge data including attestation/assertion for customer verification
   */
  last_webauthn_challenge_data: Json | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthAuthorizations {
  approved_at: Timestamp | null;
  authorization_code: string | null;
  authorization_id: string;
  client_id: string;
  code_challenge: string | null;
  code_challenge_method: AuthCodeChallengeMethod | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: string;
  nonce: string | null;
  redirect_uri: string;
  resource: string | null;
  response_type: Generated<AuthOauthResponseType>;
  scope: string;
  state: string | null;
  status: Generated<AuthOauthAuthorizationStatus>;
  user_id: string | null;
}

export interface AuthOauthClients {
  client_name: string | null;
  client_secret_hash: string | null;
  client_type: Generated<AuthOauthClientType>;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  token_endpoint_auth_method: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthOauthClientStates {
  code_verifier: string | null;
  created_at: Timestamp;
  id: string;
  provider_type: string;
}

export interface AuthOauthConsents {
  client_id: string;
  granted_at: Generated<Timestamp>;
  id: string;
  revoked_at: Timestamp | null;
  scopes: string;
  user_id: string;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  oauth_client_id: string | null;
  /**
   * Holds the ID (counter) of the last issued refresh token.
   */
  refresh_token_counter: Int8 | null;
  /**
   * Holds a HMAC-SHA256 key used to sign refresh tokens for this session.
   */
  refresh_token_hmac_key: string | null;
  refreshed_at: Timestamp | null;
  scopes: string | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface AuthWebauthnChallenges {
  challenge_type: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  session_data: Json;
  user_id: string | null;
}

export interface AuthWebauthnCredentials {
  aaguid: string | null;
  attestation_type: Generated<string>;
  backed_up: Generated<boolean>;
  backup_eligible: Generated<boolean>;
  created_at: Generated<Timestamp>;
  credential_id: Buffer;
  friendly_name: Generated<string>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  public_key: Buffer;
  sign_count: Generated<Int8>;
  transports: Generated<Json>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Certifications {
  category: Certificationcategory | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  difficulty: Difficultylevel | null;
  id: string;
  issuing_organization_id: string | null;
  jobs: string[] | null;
  level: string | null;
  metadata: Json | null;
  name: string;
  products: string[] | null;
  score: number | null;
  serialNumber: string;
  updated_at: Timestamp;
  validity_duration_months: number | null;
  website_url: string | null;
}

export interface Cities {
  average_rent: number | null;
  climate: string | null;
  cost_of_living: Costofliving | null;
  country_id: string;
  created_at: Generated<Timestamp>;
  degree_holders: string | null;
  deleted_at: Timestamp | null;
  id: string;
  interesting_fact: string | null;
  is_capital: Generated<boolean>;
  language: Language | null;
  largest_organization: string | null;
  latitude: number | null;
  longitude: number | null;
  median_home_price: number | null;
  median_salary: number | null;
  metadata: Json | null;
  name: string;
  number_of_airports: number | null;
  number_of_multinational_hqs: number | null;
  number_of_nationalities: number | null;
  number_of_universities: number | null;
  people_description: string | null;
  population: number | null;
  serial_number: string;
  state_province: string | null;
  temperatures: string | null;
  top_universities: string | null;
  updated_at: Timestamp;
}

export interface Countries {
  area_km2: number | null;
  average_rent: number | null;
  calling_code: string | null;
  capital_name: string | null;
  citizenship_process: string | null;
  climate: string | null;
  cost_of_living: Costofliving | null;
  created_at: Generated<Timestamp>;
  crime_rate: string | null;
  cultural_values: string | null;
  currency: string | null;
  degree_holders: string | null;
  deleted_at: Timestamp | null;
  ethnic_groups: string[] | null;
  flag_url: string | null;
  gdp_per_capita_usd: number | null;
  gdp_usd: number | null;
  global_competitiveness_index: number | null;
  government_type: Governmenttype | null;
  hdi: number | null;
  id: string;
  income_inequality: string | null;
  interesting_fact: string | null;
  iso_code: string | null;
  level_of_globalisation: string | null;
  main_industries: string | null;
  median_home_price: number | null;
  median_salary: number | null;
  metadata: Json | null;
  name: string;
  number_of_airports: number | null;
  number_of_foreign_organizations: number | null;
  number_of_international_students: number | null;
  number_of_multinational_hqs: number | null;
  number_of_tourists: number | null;
  number_of_universities: number | null;
  officialLanguages: ArrayType<Language> | null;
  people_description: string | null;
  personal_income_tax: string | null;
  population: Int8 | null;
  quality_of_education: string | null;
  quality_of_life: Qualityoflife | null;
  religion: string[] | null;
  serial_number: string;
  temperatures: string | null;
  top_universities: string | null;
  updated_at: Timestamp;
  work_life_balance: string | null;
  work_permit: string | null;
}

export interface Degrees {
  area: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  duration_years: number | null;
  id: string;
  level: Degreelevel | null;
  metadata: Json | null;
  name: string;
  score: number | null;
  serialNumber: string;
  updated_at: Timestamp;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Industries {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  icon_url: string | null;
  id: string;
  metadata: Json | null;
  name: string;
  score: number | null;
  serialNumber: string;
  updated_at: Timestamp;
}

export interface JobAds {
  application_email: string | null;
  application_url: string | null;
  city_id: string | null;
  contract_type: Contracttype | null;
  country_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  expires_at: Timestamp | null;
  id: string;
  job_id: string | null;
  metadata: Json | null;
  organization_id: string;
  published_at: Timestamp | null;
  remote: Remotepolicy | null;
  required_education_level: Educationlevel | null;
  required_years_experience: number | null;
  salary_range: string | null;
  serial_number: string;
  status: Generated<Jobadstatus>;
  tags: string[] | null;
  title: string;
  updated_at: Timestamp;
}

export interface JobAdSkills {
  id: string;
  importance: Generated<Skillimportance>;
  job_ad_id: string;
  skill_id: string;
}

export interface Jobs {
  category: Jobcategory | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  industry_id: string | null;
  metadata: Json | null;
  products: string[] | null;
  score: number | null;
  seniority_level: Senioritylevel | null;
  serialNumber: string;
  tags: string[] | null;
  title: string;
  tools_and_tech: string[] | null;
  updated_at: Timestamp;
}

export interface Majors {
  area: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: string;
  metadata: Json | null;
  name: string;
  score: number | null;
  serial_number: string;
  updated_at: Timestamp;
}

export interface MilitaryCapabilities {
  id: string;
  number_of_active_navy_personnel: number | null;
  number_of_aircrafts: number | null;
  number_of_communication_satellites: number | null;
  number_of_destroyers: number | null;
  number_of_drones: number | null;
  number_of_fighter_jets: number | null;
  number_of_helicopters: number | null;
  number_of_maritime_patrol_aircraft: number | null;
  number_of_missile_warning_satellites: number | null;
  number_of_naval_shipyards: number | null;
  number_of_navigation_satellites: number | null;
  number_of_operational_spaceplanes: number | null;
  number_of_satellite_jamming_systems: number | null;
  number_of_space_launch_sites: number | null;
  number_of_space_operations_squadrons: number | null;
  number_of_space_personnel: number | null;
  number_of_spy_satellites: number | null;
  number_of_stealth_fleet: number | null;
  number_of_submarines_diesel: number | null;
  number_of_submarines_nuclear: number | null;
  number_of_surveillance_radars: number | null;
  number_of_surveillance_telescopes: number | null;
  number_of_tanker_planes: number | null;
  number_of_transport_planes: number | null;
  organization_id: string;
  updated_at: Timestamp;
}

export interface Organizations {
  activities: string[] | null;
  budget: string | null;
  category: string | null;
  city_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  equipments: string | null;
  founded: string | null;
  founder: string | null;
  id: string;
  known_for: string[] | null;
  legal_status: string | null;
  metadata: Json | null;
  mission: string | null;
  name: string;
  numberOfEmployees: Employeecountrange | null;
  numberOfSubsidiaries: number | null;
  ownership: string | null;
  parent_organization_id: string | null;
  partnerships: string[] | null;
  products: string[] | null;
  project: string | null;
  research_areas: string[] | null;
  score: number | null;
  services: string[] | null;
  slug: string;
  type: Organizationsubtype | null;
  updated_at: Timestamp;
}

export interface RealtimeMessages {
  binary_payload: Buffer | null;
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  action_filter: Generated<string | null>;
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  selected_columns: string[] | null;
  subscription_id: string;
}

export interface Skills {
  categories: string[] | null;
  category: Skillcategory | null;
  common_fields_of_study: string[] | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  difficulty: Difficultylevel | null;
  icon_url: string | null;
  id: string;
  industry: string | null;
  jobs: string[] | null;
  metadata: Json | null;
  name: string;
  product_categories: string[] | null;
  related_abilities: string[] | null;
  score: number | null;
  serialNumber: string;
  time_to_master: string | null;
  type: string | null;
  updated_at: Timestamp;
  used_in: string[] | null;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  format: Generated<string>;
  id: Generated<string>;
  name: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageBucketsVectors {
  created_at: Generated<Timestamp>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  metadata: Json | null;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface StorageVectorIndexes {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  data_type: string;
  dimension: number;
  distance_metric: string;
  id: Generated<string>;
  metadata_configuration: Json | null;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Subjects {
  category: Subjectcategory | null;
  competitors: string[] | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  fun_fact: string | null;
  id: string;
  logo_url: string | null;
  metadata: Json | null;
  name: string;
  organization_id: string | null;
  score: number | null;
  serialNumber: string;
  short_description: string | null;
  tags: string[] | null;
  type: string | null;
  updated_at: Timestamp;
  website_url: string | null;
}

export interface Universities {
  city_id: string | null;
  country_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  established: string | null;
  id: string;
  local_name: string | null;
  logo_url: string | null;
  metadata: Json | null;
  name: string;
  notes: string | null;
  postgraduates: number | null;
  score: number | null;
  score_university: number | null;
  serialNumber: string;
  student_count: number | null;
  type: Universitytype | null;
  undergraduates: number | null;
  updated_at: Timestamp;
  website_url: string | null;
}

export interface UserCertifications {
  certification_id: string;
  expires_at: Timestamp | null;
  id: string;
  obtained_at: Timestamp | null;
  user_profile_id: string;
}

export interface UserEducations {
  degree_id: string | null;
  end_year: number | null;
  graduated: Generated<boolean>;
  id: string;
  major_id: string | null;
  start_year: number | null;
  university_id: string | null;
  user_profile_id: string;
}

export interface UserProfiles {
  biography: string | null;
  city_id: string | null;
  country_id: string | null;
  created_at: Generated<Timestamp>;
  current_job_id: string | null;
  current_job_started_at: Timestamp | null;
  current_organization_id: string | null;
  github_url: string | null;
  id: string;
  is_public: Generated<boolean>;
  linkedin_url: string | null;
  locale: Generated<string | null>;
  metadata: Json | null;
  timezone: string | null;
  updated_at: Timestamp;
  user_id: string;
  website_url: string | null;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  display_name: string | null;
  email: string;
  email_verified: Generated<boolean>;
  failed_login_attempts: Generated<number>;
  first_name: string | null;
  id: string;
  last_login_at: Timestamp | null;
  last_name: string | null;
  last_reset_sent_at: Timestamp | null;
  last_verification_sent_at: Timestamp | null;
  locked_until: Timestamp | null;
  marketing_opt_in: Generated<boolean>;
  metadata: Json | null;
  organization_id: string | null;
  password_changed_at: Timestamp | null;
  password_hash: string;
  reset_expires_at: Timestamp | null;
  reset_token: string | null;
  role: Generated<Userrole>;
  status: Generated<Userstatus>;
  updated_at: Timestamp;
  verification_code: string | null;
  verification_expires_at: Timestamp | null;
}

export interface UserSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  ip_address: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  _CityMainIndustries: _CityMainIndustries;
  _CountryLargestOrganizations: _CountryLargestOrganizations;
  _OrganizationIndustries: _OrganizationIndustries;
  _prisma_migrations: _PrismaMigrations;
  _ProductIndustries: _ProductIndustries;
  _RelatedIndustries: _RelatedIndustries;
  _working_area: _WorkingArea;
  audit_logs: AuditLogs;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.custom_oauth_providers": AuthCustomOauthProviders;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_authorizations": AuthOauthAuthorizations;
  "auth.oauth_client_states": AuthOauthClientStates;
  "auth.oauth_clients": AuthOauthClients;
  "auth.oauth_consents": AuthOauthConsents;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  "auth.webauthn_challenges": AuthWebauthnChallenges;
  "auth.webauthn_credentials": AuthWebauthnCredentials;
  certifications: Certifications;
  cities: Cities;
  countries: Countries;
  degrees: Degrees;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  industries: Industries;
  job_ad_skills: JobAdSkills;
  job_ads: JobAds;
  jobs: Jobs;
  majors: Majors;
  military_capabilities: MilitaryCapabilities;
  organizations: Organizations;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  skills: Skills;
  "storage.buckets": StorageBuckets;
  "storage.buckets_analytics": StorageBucketsAnalytics;
  "storage.buckets_vectors": StorageBucketsVectors;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  "storage.vector_indexes": StorageVectorIndexes;
  subjects: Subjects;
  universities: Universities;
  user_certifications: UserCertifications;
  user_educations: UserEducations;
  user_profiles: UserProfiles;
  user_sessions: UserSessions;
  users: Users;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
}
