import { z } from "zod";
import { CostOfLivingSchema, LanguageSchema } from "./countries";

export const CostOfLivingEnum = z.enum(["LOW", "MEDIAN", "HIGH"]);
export const LanguageEnum = z.enum([
  "AFRIKAANS",
  "ALBANIAN",
  "AMHARIC",
  "ARABIC",
  "ARMENIAN",
  "AZERBAIJANI",
  "BASQUE",
  "BELARUSIAN",
  "BENGALI",
  "BOSNIAN",
  "BULGARIAN",
  "BURMESE",
  "CATALAN",
  "CEBUANO",
  "CHINESE_CANTONESE",
  "CHINESE_MANDARIN",
  "CROATIAN",
  "CZECH",
  "DANISH",
  "DUTCH",
  "ENGLISH",
  "ESPERANTO",
  "ESTONIAN",
  "FILIPINO",
  "FINNISH",
  "FRENCH",
  "GALICIAN",
  "GEORGIAN",
  "GERMAN",
  "GREEK",
  "GUJARATI",
  "HAITIAN_CREOLE",
  "HAUSA",
  "HEBREW",
  "HINDI",
  "HUNGARIAN",
  "ICELANDIC",
  "IGBO",
  "INDONESIAN",
  "IRISH",
  "ITALIAN",
  "JAPANESE",
  "JAVANESE",
  "KANNADA",
  "KAZAKH",
  "KHMER",
  "KOREAN",
  "KURDISH",
  "KYRGYZ",
  "LAO",
  "LATIN",
  "LATVIAN",
  "LITHUANIAN",
  "LUXEMBOURGISH",
  "MACEDONIAN",
  "MALAGASY",
  "MALAY",
  "MALAYALAM",
  "MALTESE",
  "MAORI",
  "MARATHI",
  "MONGOLIAN",
  "NEPALI",
  "NORWEGIAN",
  "PASHTO",
  "PERSIAN",
  "POLISH",
  "PORTUGUESE",
  "PUNJABI",
  "ROMANIAN",
  "RUSSIAN",
  "SAMOAN",
  "SERBIAN",
  "SHONA",
  "SINDHI",
  "SINHALA",
  "SLOVAK",
  "SLOVENIAN",
  "SOMALI",
  "SPANISH",
  "SUNDANESE",
  "SWAHILI",
  "SWEDISH",
  "TAJIK",
  "TAMIL",
  "TATAR",
  "TELUGU",
  "THAI",
  "TIBETAN",
  "TURKISH",
  "TURKMEN",
  "UKRAINIAN",
  "URDU",
  "UZBEK",
  "VIETNAMESE",
  "WELSH",
  "WOLOF",
  "XHOSA",
  "YIDDISH",
  "YORUBA",
  "ZULU",
]);

export const CitySchema = z.object({
  id: z.string().uuid(),
  name: z.string().trim().min(1),
  serialNumber: z.string().trim().min(1),
  country_id: z.string().uuid(),
  is_capital: z.boolean().optional().default(false),
  state_province: z.string().nullable().optional(),
  population: z.number().int().nullable().optional(),
  number_of_multinational_hqs: z.number().int().nullable().optional(),
  number_of_airports: z.number().int().nullable().optional(),
  median_salary: z.number().int().nullable().optional(),
  cost_of_living: CostOfLivingSchema.nullable().optional(),
  median_home_price: z.number().int().nullable().optional(),
  average_rent: z.number().int().nullable().optional(),
  temperatures: z.string().nullable().optional(),
  climate: z.string().nullable().optional(),
  interesting_fact: z.string().nullable().optional(),
  degree_holders: z.string().nullable().optional(),
  number_of_universities: z.number().int().nullable().optional(),
  number_of_nationalities: z.number().int().nullable().optional(),
  language: LanguageSchema.nullable().optional(),
  people_description: z.string().nullable().optional(),
  latitude: z.number().nullable().optional(),
  longitude: z.number().nullable().optional(),
  metadata: z.any().nullable().optional(),
  deleted_at: z
    .date()
    .nullable()
    .optional()
    .default(null as any),
  created_at: z.date().default(new Date()),
  updated_at: z.date().default(new Date()),
});

export const CreateCitySchema = CitySchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
  serialNumber: true,
}).extend({
  serialNumber: z.string().trim().min(1),
});

export const UpdateCitySchema = CreateCitySchema.partial();

export const GetCitiesSchema = z.object({
  search: z.string().optional(),
  country_id: z.string().uuid().optional(),
});

export type City = z.infer<typeof CitySchema>;
export type CreateCity = z.infer<typeof CreateCitySchema>;
export type UpdateCity = z.infer<typeof UpdateCitySchema>;
