import { z } from "zod";

export const OrganizationTypeEnum = z.enum(["COMPANY", "GOVERNMENT_MINISTRY", "INTERNATIONAL_ORG", "MILITARY", "NGO", "OTHER", "POLITICAL_PARTY", "RESEARCH_INSTITUTE", "STARTUP"]);
export const EmployeeCountRangeEnum = z.enum(["RANGE_1_10", "RANGE_1001_5000", "RANGE_11_50", "RANGE_201_1000", "RANGE_5000_PLUS", "RANGE_51_200"]);

export const OrganizationSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  type: OrganizationTypeEnum.nullable(),
  category: z.string().nullable(),
  subsidiaries_count: z.number().int().nullable(),
  legal_status: z.string().nullable(),
  ownership: z.string().nullable(),
  mission: z.string().nullable(),
  purpose: z.string().nullable(),
  focus: z.string().nullable(),
  focus_areas: z.array(z.string()).nullable(),
  strategic_focus: z.string().nullable(),
  known_for: z.array(z.string()).nullable(),
  distinction: z.string().nullable(),
  fields: z.array(z.string()).nullable(),
  key_activities: z.array(z.string()).nullable(),
  key_project: z.string().nullable(),
  key_research_output: z.string().nullable(),
  major_programs: z.array(z.string()).nullable(),
  major_projects: z.array(z.string()).nullable(),
  research_areas: z.array(z.string()).nullable(),
  research_model: z.string().nullable(),
  business_and_innovation: z.string().nullable(),
  products: z.array(z.string()).nullable(),
  services: z.array(z.string()).nullable(),
  management_and_admin: z.string().nullable(),
  main_organ: z.string().nullable(),
  constituency: z.string().nullable(),
  affiliation: z.string().nullable(),
  collaborations: z.array(z.string()).nullable(),
  partnerships: z.array(z.string()).nullable(),
  funding_sources: z.array(z.string()).nullable(),
  budget: z.string().nullable(),
  endowment: z.string().nullable(),
  gdp: z.string().nullable(),
  founded: z.string().nullable(),
  formed: z.string().nullable(),
  formation: z.string().nullable(),
  opened: z.string().nullable(),
  dissolved: z.string().nullable(),
  founder: z.string().nullable(),
  headquarters: z.string().nullable(),
  location: z.string().nullable(),
  region_served: z.string().nullable(),
  geography: z.string().nullable(),
  total_land_area: z.string().nullable(),
  population_of_city: z.string().nullable(),
  number_of_offices: z.number().int().nullable(),
  numberOfEmployees: EmployeeCountRangeEnum.nullable(),
  number_of_members: z.number().int().nullable(),
  number_of_personnel: z.number().int().nullable(),
  number_of_volunteers: z.number().int().nullable(),
  number_of_government_ministries: z.number().int().nullable(),
  number_of_ministries: z.number().int().nullable(),
  scale: z.string().nullable(),
  size: z.string().nullable(),
  visitors: z.string().nullable(),
  labs: z.array(z.string()).nullable(),
  giant_facilities: z.array(z.string()).nullable(),
  national_parks: z.array(z.string()).nullable(),
  libraries_and_publications: z.string().nullable(),
  tactical_units: z.array(z.string()).nullable(),
  parent_organization_id: z.string().uuid().nullable(),
  parent_bureau: z.string().nullable(),
  parent_department: z.string().nullable(),
  parent_ministry: z.string().nullable(),
  preceding_agency: z.string().nullable(),
  preceding_bureau: z.string().nullable(),
  preceding_department: z.string().nullable(),
  superseding_agencies: z.array(z.string()).nullable(),
  superseding_postal_system: z.string().nullable(),
  number_of_active_navy_personnel: z.number().int().nullable(),
  number_of_destroyers: z.number().int().nullable(),
  number_of_submarines_diesel: z.number().int().nullable(),
  number_of_submarines_nuclear: z.number().int().nullable(),
  number_of_naval_shipyards: z.number().int().nullable(),
  number_of_maritime_patrol_aircraft: z.number().int().nullable(),
  number_of_stealth_fleet: z.number().int().nullable(),
  number_of_surveillance_radars: z.number().int().nullable(),
  number_of_aircrafts: z.number().int().nullable(),
  number_of_fighter_jets: z.number().int().nullable(),
  number_of_helicopters: z.number().int().nullable(),
  number_of_drones: z.number().int().nullable(),
  number_of_tanker_planes: z.number().int().nullable(),
  number_of_transport_planes: z.number().int().nullable(),
  number_of_communication_satellites: z.number().int().nullable(),
  number_of_missile_warning_satellites: z.number().int().nullable(),
  number_of_navigation_satellites: z.number().int().nullable(),
  number_of_spy_satellites: z.number().int().nullable(),
  number_of_satellite_jamming_systems: z.number().int().nullable(),
  number_of_surveillance_telescopes: z.number().int().nullable(),
  number_of_operational_spaceplanes: z.number().int().nullable(),
  number_of_space_launch_sites: z.number().int().nullable(),
  number_of_space_operations_squadrons: z.number().int().nullable(),
  number_of_space_personnel: z.number().int().nullable(),
  metadata: z.unknown().nullable(),
  deleted_at: z.date().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const CreateOrganizationSchema = OrganizationSchema.omit({
  id: true,
  created_at: true,
  updated_at: true,
  deleted_at: true,
});

export const UpdateOrganizationSchema = CreateOrganizationSchema.partial();

export const GetOrganizationsSchema = z.object({
  search: z.string().optional(),
  type: OrganizationTypeEnum.optional(),
});

export type Organization = z.infer<typeof OrganizationSchema>;
export type CreateOrganization = z.infer<typeof CreateOrganizationSchema>;
export type UpdateOrganization = z.infer<typeof UpdateOrganizationSchema>;